In [1]:
import pandas as pd

In [2]:
df = pd.read_json('/Users/leenaomrani/Desktop/final-project/data_jobs_france/all_data_France_details.json')
df.head()

,url_offre,descriptif_job,tags
0,https://www.hellowork.com/fr-fr/emplois/343856...,"[\n\t\t\t\tCabinet de recrutement Tech, la mis...",[\n Services aux Entreprises\n ...
1,https://www.hellowork.com/fr-fr/emplois/301698...,"[\n Présentation Entreprise :, ...",[]
2,https://www.hellowork.com/fr-fr/emplois/345666...,[\n Join us and BE a pioneer fo...,[]
3,https://www.hellowork.com/fr-fr/emplois/341386...,[\n AVENTA identifie les meille...,[]
4,https://www.hellowork.com/fr-fr/emplois/341710...,"[\n Rhapsodies conseil, un cabi...",[]

In [3]:
import re

In [4]:
df['descriptif_job'] = [''.join(map(str, d)) for d in df['descriptif_job']]
df['tags'] = [''.join(map(str, d)) for d in df['tags']]
df

,url_offre,descriptif_job,tags
0,https://www.hellowork.com/fr-fr/emplois/343856...,"\n\t\t\t\tCabinet de recrutement Tech, la miss...",\n Services aux Entreprises\n ...
1,https://www.hellowork.com/fr-fr/emplois/301698...,\n Présentation Entreprise :GUA...,
2,https://www.hellowork.com/fr-fr/emplois/345666...,\n Join us and BE a pioneer for...,
3,https://www.hellowork.com/fr-fr/emplois/341386...,\n AVENTA identifie les meilleu...,
4,https://www.hellowork.com/fr-fr/emplois/341710...,"\n Rhapsodies conseil, un cabin...",
...,...,...,...
9175,https://www.hellowork.com/fr-fr/emplois/317556...,\n Qui sont-ils ?Depuis plus de...,
9176,https://www.hellowork.com/fr-fr/emplois/323667...,\n Our mission? Creating the fi...,
9177,https://www.hellowork.com/fr-fr/emplois/317556...,\n Qui sont-ils ?Depuis plus de...,
9178,https://www.hellowork.com/fr-fr/emplois/311708...,\n Qui sont-ils ?Depuis plus de...,
9179,https://www.hellowork.com/fr-fr/emplois/334352...,"\n Groupe de Luxe mondial, Keri...",

In [5]:
df['descriptif_job'] = df['descriptif_job'].str.replace('\n',' ')
df

,url_offre,descriptif_job,tags
0,https://www.hellowork.com/fr-fr/emplois/343856...,"\t\t\t\tCabinet de recrutement Tech, la missi...",\n Services aux Entreprises\n ...
1,https://www.hellowork.com/fr-fr/emplois/301698...,Présentation Entreprise :GUAR...,
2,https://www.hellowork.com/fr-fr/emplois/345666...,Join us and BE a pioneer for ...,
3,https://www.hellowork.com/fr-fr/emplois/341386...,AVENTA identifie les meilleur...,
4,https://www.hellowork.com/fr-fr/emplois/341710...,"Rhapsodies conseil, un cabine...",
...,...,...,...
9175,https://www.hellowork.com/fr-fr/emplois/317556...,Qui sont-ils ?Depuis plus de ...,
9176,https://www.hellowork.com/fr-fr/emplois/323667...,Our mission? Creating the fin...,
9177,https://www.hellowork.com/fr-fr/emplois/317556...,Qui sont-ils ?Depuis plus de ...,
9178,https://www.hellowork.com/fr-fr/emplois/311708...,Qui sont-ils ?Depuis plus de ...,
9179,https://www.hellowork.com/fr-fr/emplois/334352...,"Groupe de Luxe mondial, Kerin...",

In [6]:
df['descriptif_job'] = df['descriptif_job'].str.replace('\t',' ')
df

,url_offre,descriptif_job,tags
0,https://www.hellowork.com/fr-fr/emplois/343856...,"Cabinet de recrutement Tech, la mission d...",\n Services aux Entreprises\n ...
1,https://www.hellowork.com/fr-fr/emplois/301698...,Présentation Entreprise :GUAR...,
2,https://www.hellowork.com/fr-fr/emplois/345666...,Join us and BE a pioneer for ...,
3,https://www.hellowork.com/fr-fr/emplois/341386...,AVENTA identifie les meilleur...,
4,https://www.hellowork.com/fr-fr/emplois/341710...,"Rhapsodies conseil, un cabine...",
...,...,...,...
9175,https://www.hellowork.com/fr-fr/emplois/317556...,Qui sont-ils ?Depuis plus de ...,
9176,https://www.hellowork.com/fr-fr/emplois/323667...,Our mission? Creating the fin...,
9177,https://www.hellowork.com/fr-fr/emplois/317556...,Qui sont-ils ?Depuis plus de ...,
9178,https://www.hellowork.com/fr-fr/emplois/311708...,Qui sont-ils ?Depuis plus de ...,
9179,https://www.hellowork.com/fr-fr/emplois/334352...,"Groupe de Luxe mondial, Kerin...",

In [7]:
df['url_offre']

0       https://www.hellowork.com/fr-fr/emplois/343856...
1       https://www.hellowork.com/fr-fr/emplois/301698...
2       https://www.hellowork.com/fr-fr/emplois/345666...
3       https://www.hellowork.com/fr-fr/emplois/341386...
4       https://www.hellowork.com/fr-fr/emplois/341710...
                              ...
9175    https://www.hellowork.com/fr-fr/emplois/317556...
9176    https://www.hellowork.com/fr-fr/emplois/323667...
9177    https://www.hellowork.com/fr-fr/emplois/317556...
9178    https://www.hellowork.com/fr-fr/emplois/311708...
9179    https://www.hellowork.com/fr-fr/emplois/334352...
Name: url_offre, Length: 9180, dtype: object

In [8]:
def extract_id_offre(url_offre):
    match = re.search(r'/(\d+)\.html', url_offre)
    if match:
        return match.group(1)
    else:
        return None

# apply the function to the 'url' column and create a new 'number' column
df['id_offre'] = df['url_offre'].apply(extract_id_offre)

# print the resulting DataFrame
print(df)

                                              url_offre  \
0     https://www.hellowork.com/fr-fr/emplois/343856...
1     https://www.hellowork.com/fr-fr/emplois/301698...
2     https://www.hellowork.com/fr-fr/emplois/345666...
3     https://www.hellowork.com/fr-fr/emplois/341386...
4     https://www.hellowork.com/fr-fr/emplois/341710...
...                                                 ...
9175  https://www.hellowork.com/fr-fr/emplois/317556...
9176  https://www.hellowork.com/fr-fr/emplois/323667...
9177  https://www.hellowork.com/fr-fr/emplois/317556...
9178  https://www.hellowork.com/fr-fr/emplois/311708...
9179  https://www.hellowork.com/fr-fr/emplois/334352...

                                         descriptif_job  \
0          Cabinet de recrutement Tech, la mission d...
1                      Présentation Entreprise :GUAR...
2                      Join us and BE a pioneer for ...
3                      AVENTA identifie les meilleur...
4                      Rhapsodies conseil, un cabine...
...                                                 ...
9175                   Qui sont-ils ?Depuis plus de ...
9176                   Our mission? Creating the fin...
9177                   Qui sont-ils ?Depuis plus de ...
9178                   Qui sont-ils ?Depuis plus de ...
9179                   Groupe de Luxe mondial, Kerin...

                                                   tags  id_offre
0     \n                Services aux Entreprises\n  ...  34385664
1                                                        30169855
2                                                        34566667
3                                                        34138643
4                                                        34171047
...                                                 ...       ...
9175                                                     31755612
9176                                                     32366790
9177                                                     31755609
9178                                                     31170856
9179                                                     33435291

[9180 rows x 4 columns]

In [9]:
#supprimer les doublons
result_df = df.drop_duplicates(keep='last')
print(result_df)

                                              url_offre  \
0     https://www.hellowork.com/fr-fr/emplois/347261...
1     https://www.hellowork.com/fr-fr/emplois/318534...
2     https://www.hellowork.com/fr-fr/emplois/333902...
3     https://www.hellowork.com/fr-fr/emplois/347509...
4     https://www.hellowork.com/fr-fr/emplois/333902...
...                                                 ...
1294  https://www.hellowork.com/fr-fr/emplois/337457...
1295  https://www.hellowork.com/fr-fr/emplois/324310...
1296  https://www.hellowork.com/fr-fr/emplois/341645...
1297  https://www.hellowork.com/fr-fr/emplois/327460...
1298  https://www.hellowork.com/fr-fr/emplois/326691...

                                         descriptif_job tags  id_offre
0                      IA Recrutement est une agence...       34726178
1                      IA Recrutement est une agence...       31853486
2                      IA Recrutement est une agence...       33390276
3                      IA Recrutement est une agence...       34750924
4                      IA Recrutement est une agence...       33390256
...                                                 ...  ...       ...
1294                                                          33745716
1295                   Informations généralesEntité ...       32431012
1296                   Dans un monde où savoir se tr...       34164594
1297                   Dans un monde où savoir se tr...       32746050
1298                   Qui sont-ils ?Depuis plus de ...       32669175

[1284 rows x 4 columns]

NameError: name 'result_df' is not defined

In [10]:
df

,url_offre,descriptif_job,tags,id_offre
0,https://www.hellowork.com/fr-fr/emplois/343856...,"Cabinet de recrutement Tech, la mission d...",\n Services aux Entreprises\n ...,34385664
1,https://www.hellowork.com/fr-fr/emplois/301698...,Présentation Entreprise :GUAR...,,30169855
2,https://www.hellowork.com/fr-fr/emplois/345666...,Join us and BE a pioneer for ...,,34566667
3,https://www.hellowork.com/fr-fr/emplois/341386...,AVENTA identifie les meilleur...,,34138643
4,https://www.hellowork.com/fr-fr/emplois/341710...,"Rhapsodies conseil, un cabine...",,34171047
...,...,...,...,...
9175,https://www.hellowork.com/fr-fr/emplois/317556...,Qui sont-ils ?Depuis plus de ...,,31755612
9176,https://www.hellowork.com/fr-fr/emplois/323667...,Our mission? Creating the fin...,,32366790
9177,https://www.hellowork.com/fr-fr/emplois/317556...,Qui sont-ils ?Depuis plus de ...,,31755609
9178,https://www.hellowork.com/fr-fr/emplois/311708...,Qui sont-ils ?Depuis plus de ...,,31170856
9179,https://www.hellowork.com/fr-fr/emplois/334352...,"Groupe de Luxe mondial, Kerin...",,33435291

In [12]:
df.to_csv('/Users/leenaomrani/Desktop/final-project/data_jobs_france/data_description.csv')

In [13]:
#chargement dataset
df_summary = pd.read_csv("/Users/leenaomrani/Desktop/final-project/data_jobs_france/jobs_data_france.csv", index_col=0)
df_description= pd.read_csv("/Users/leenaomrani/Desktop/final-project/data_jobs_france/data_description.csv", index_col=0)

In [14]:
df_summary

,id_offre,entreprise,type_contrat,localisation,modalites_de_tetetravail,url,duree_du_contrat,tag recruteur_reactif,titre_job,date_publication
0,31853486,IA Recrutement,CDI,Saint-Sulpice-et-Cameyrac - 33,NaN,https://www.hellowork.com/fr-fr/emplois/318534...,NaN,NaN,Chef d'Équipe Couvreu...,...
1,33390214,IA Recrutement,Intérim,Saint-Émilion - 33,NaN,https://www.hellowork.com/fr-fr/emplois/333902...,NaN,NaN,Plombier-Chauffagiste...,...
2,30777814,IA Recrutement,Intérim,Pompignac - 33,NaN,https://www.hellowork.com/fr-fr/emplois/307778...,NaN,NaN,Plombier Chauffagiste...,...
3,33390276,IA Recrutement,Intérim,Bordeaux - 33,NaN,https://www.hellowork.com/fr-fr/emplois/333902...,NaN,NaN,Manoeuvre H/F ...,il y a 22 heures ...
4,33390256,IA Recrutement,Intérim,Bordeaux - 33,NaN,https://www.hellowork.com/fr-fr/emplois/333902...,NaN,NaN,Etancheur H/F ...,il y a 22 heures ...
...,...,...,...,...,...,...,...,...,...,...
1294,33745716,Lasecurecrute.fr,CDI,Montauban - 82,Télétravail partiel,https://www.hellowork.com/fr-fr/emplois/337457...,NaN,NaN,Responsable du Servic...,04/04/2023 ...
1295,34164594,Wavestone,CDI,Paris 1er - 75,NaN,https://www.hellowork.com/fr-fr/emplois/341645...,NaN,NaN,Consultant·e en Trans...,14/04/2023 ...
1296,32746050,Wavestone,CDI,Paris 1er - 75,NaN,https://www.hellowork.com/fr-fr/emplois/327460...,NaN,NaN,Consultant.e en Trans...,11/04/2023 ...
1297,32669175,Decathlon Technology,CDI,Croix - 59,Télétravail partiel,https://www.hellowork.com/fr-fr/emplois/326691...,NaN,NaN,Product Manager - Dat...,11/04/2023 ...
1298,32431012,Air France,CDI,Valbonne - 06,NaN,https://www.hellowork.com/fr-fr/emplois/324310...,NaN,NaN,Software Engineer H/F...,06/04/2023 ...

In [15]:
df_description

,url_offre,descriptif_job,tags,id_offre
0,https://www.hellowork.com/fr-fr/emplois/347261...,IA Recrutement est une agence...,NaN,34726178
1,https://www.hellowork.com/fr-fr/emplois/318534...,IA Recrutement est une agence...,NaN,31853486
2,https://www.hellowork.com/fr-fr/emplois/333902...,IA Recrutement est une agence...,NaN,33390276
3,https://www.hellowork.com/fr-fr/emplois/347509...,IA Recrutement est une agence...,NaN,34750924
4,https://www.hellowork.com/fr-fr/emplois/333902...,IA Recrutement est une agence...,NaN,33390256
...,...,...,...,...
1294,https://www.hellowork.com/fr-fr/emplois/337457...,NaN,NaN,33745716
1295,https://www.hellowork.com/fr-fr/emplois/324310...,Informations généralesEntité ...,NaN,32431012
1296,https://www.hellowork.com/fr-fr/emplois/341645...,Dans un monde où savoir se tr...,NaN,34164594
1297,https://www.hellowork.com/fr-fr/emplois/327460...,Dans un monde où savoir se tr...,NaN,32746050
1298,https://www.hellowork.com/fr-fr/emplois/326691...,Qui sont-ils ?Depuis plus de ...,NaN,32669175

In [14]:
# suppression doublons
df_summary = df_summary.drop_duplicates(keep='last')
df_description = df_description.drop_duplicates(keep='last')

In [15]:
df_data_jobs_merged = pd.merge(df_summary, df_description, on="id_offre").drop_duplicates(keep='last')
df_data_jobs_merged

,id_offre,entreprise,type_contrat,localisation,date_de_publication,modalites_de_tetetravail,url,duree_du_contrat,tag recruteur_reactif,titre_job,date_publication,url_offre,descriptif_job,tags
0,34566667,AUTOMOTIVE CELLS COMPANY - ACC,CDI ...,Bordeaux - 33,['\n 24/04/2023\n ...,Télétravail occasionnel,https://www.hellowork.com/fr-fr/emplois/345666...,NaN,NaN,Head Of Data Engineer...,24/04/2023 ...,https://www.hellowork.com/fr-fr/emplois/345666...,Join us and BE a pioneer for ...,NaN
1,33126348,Expleo,CDI ...,Montigny-le-Bretonneux - 78,['\n 21/04/2023\n ...,NaN,https://www.hellowork.com/fr-fr/emplois/331263...,NaN,NaN,Docteur - R&D - Data ...,21/04/2023 ...,https://www.hellowork.com/fr-fr/emplois/331263...,En savoir plus :Expleo propose une offre ...,NaN
2,34171047,Rhapsodies Conseil,CDI ...,Paris 8e - 75,['\n 14/04/2023\n ...,NaN,https://www.hellowork.com/fr-fr/emplois/341710...,NaN,NaN,Manager Data Privacy ...,14/04/2023 ...,https://www.hellowork.com/fr-fr/emplois/341710...,"Rhapsodies conseil, un cabine...",NaN
3,28529628,Metsys,CDI ...,Strasbourg - 67,['\n il y a 15 heures\n...,Télétravail partiel,https://www.hellowork.com/fr-fr/emplois/285296...,NaN,NaN,Consultant Senior Dat...,il y a 15 heures ...,https://www.hellowork.com/fr-fr/emplois/285296...,Nous recherchons un(e) Consultant(e) seni...,NaN
4,34026902,Inetum,CDI ...,Lyon - 69,['\n 11/04/2023\n ...,NaN,https://www.hellowork.com/fr-fr/emplois/340269...,NaN,NaN,Data Tech Lead H/F ...,11/04/2023 ...,https://www.hellowork.com/fr-fr/emplois/340269...,"Nous sommes une ESN agile, un groupe inte...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9056,32366790,Qonto,CDI ...,Paris 1er - 75,['\n 04/04/2023\n ...,Télétravail partiel,https://www.hellowork.com/fr-fr/emplois/323667...,NaN,NaN,Senior Software Engin...,04/04/2023 ...,https://www.hellowork.com/fr-fr/emplois/323667...,Our mission? Creating the fin...,NaN
9057,33435291,Kering,CDI ...,Paris 1er - 75,['\n 28/04/2023\n ...,NaN,https://www.hellowork.com/fr-fr/emplois/334352...,NaN,NaN,Kering Tech Adoption ...,28/04/2023 ...,https://www.hellowork.com/fr-fr/emplois/334352...,"Groupe de Luxe mondial, Kerin...",NaN
9058,31755609,Decathlon Technology,CDI ...,Paris 1er - 75,['\n 20/04/2023\n ...,Télétravail partiel,https://www.hellowork.com/fr-fr/emplois/317556...,NaN,NaN,Support Engineer - AP...,20/04/2023 ...,https://www.hellowork.com/fr-fr/emplois/317556...,Qui sont-ils ?Depuis plus de ...,NaN
9059,31755612,Decathlon Technology,CDI ...,Lille - 59,['\n 20/04/2023\n ...,Télétravail partiel,https://www.hellowork.com/fr-fr/emplois/317556...,NaN,NaN,Support Engineer - AP...,20/04/2023 ...,https://www.hellowork.com/fr-fr/emplois/317556...,Qui sont-ils ?Depuis plus de ...,NaN
9060,31170856,Decathlon Technology,CDI ...,Croix - 59,['\n 05/04/2023\n ...,Télétravail partiel,https://www.hellowork.com/fr-fr/emplois/311708...,NaN,NaN,Engineering Manager F...,05/04/2023 ...,https://www.hellowork.com/fr-fr/emplois/311708...,Qui sont-ils ?Depuis plus de ...,NaN

In [19]:
df_data_jobs_merged.to_csv("/Users/leenaomrani/Desktop/final-project/data_jobs_france/data_all_jobs_france.csv")